[build]
builder = "NIXPACKS"
buildCommand = "mkdir -p dist && cp server/simple-auth-server.cjs dist/server.js && echo 'Simple CommonJS server ready for Railway'"

[deploy]
startCommand = "NODE_ENV=production node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"