[build]
builder = "NIXPACKS"
buildCommand = "node build-simple.js"

[deploy]
startCommand = "NODE_ENV=production node dist/index-simple.js"
healthcheckPath = "/ping"
healthcheckTimeout = 600
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[variables]
NODE_ENV = "production"