[build]
builder = "NIXPACKS"
buildCommand = "mkdir -p dist && cp server/railway-server.js dist/server.js && echo 'ES Module server ready for Railway'"

[deploy]
startCommand = "NODE_ENV=production node dist/server.js"
healthcheckPath = "/ping"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"