[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx vite build && cp server/railway-fixed.cjs dist/server.cjs && echo 'Railway build complete'"

[deploy]
startCommand = "NODE_ENV=production node dist/server.cjs"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"