[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/ping"
healthcheckTimeout = 600
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[variables]
NODE_ENV = "production"